apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  metadata:
  - name: url
    value: https://<account>.documents.azure.com:443/
  - name: masterKey
    value: <key>
  - name: database
    value: <database>
  - name: collection
    value: orders
  - name: keyPrefix
    value: name